server:
  port: 8080

spring:



  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: user
    password: user
  cloud.stream:
    default:
      binder: rabbit
      contentType: application/json
    bindings:
      accountInsert-out-0:
        destination: account-insert
        producer:
          requiredGroups: account-insert
